### ISSUE TITLE
Moving files to subfolders causes new transfer instead of move

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1153]
Example: user changes files in folder A that have been shared for a few weeks

**scenario 1** 
rename files inside folder A
rescan
existing pieces/files are used
transfer: only few MB of meta information
:+1: 

**scenario 2**
create subfolder B inside folder A
move files to subfolder B
rescan
files are deleted from folder A
transfer: complete transfer of ALL files to folder B
:-1:

Expected: 
Syncthing should use as much of existing data as possible

**Comment by RafiKueng** [comment]
I can confirm that it works as intended:
I moved 30GB of data (in a 60GB shared folder) from one folder to another.
What happens on computer Y is that first the new files are generated (without transferring but a few MB, but it took ages never the less ;)), so the dir size goes up to 90GB, then the deletes come in and it goes back to 60GB. At least that's what I observed..

**Comment by AudriusButkevicius** [comment]
The 60 -> 90 -> 60 is expected.
The taking ages can be sort of expected, as we have to do a database look up for every 128KB, but depends what the definition of`ages` is.

**Comment by RafiKueng** [comment]
yeah, I wasn't complaining at all! Just something to be aware of (I did fill up an ssd unintentionally that way)
And I wrote ages, because I simply left it running over night while syncing to 4 other nodes, so I don't have any more precise number to give ;)

**Comment by AudriusButkevicius** [comment]
I understand that this is not a complaint. It's more of a `I'd like to know more` comment, , just in case you manage to capture the times next time, as I wrote the feature without any benchmarks :santa:

**Comment by RafiKueng** [comment]
oh, would you like some benchmarks? Let me know what you want! I'd love to help, but it might take some time, because I'm quite busy this month..

FYI: I have currently 4 machines and a mobile in sync. three machines to work on (one mobile laptop, one desktop at home, one desktop at university) and a "server" at home (to make backups, exposed to the internet) and the mobile phone for photos. So it's probably more a star configuration than a mesh. All are connected with 1 gbit/s lan / fibre; the mobile with 600mbit/s wlan (so that might not be representative)
It's handling documents (latex, word, pdf; 17gib, 33k files), projects (source codes, 5gib, 42k files), files (jpgs, mp3; 46gib, 20k) and virtual_machines (disk images, 30gib, 55 files)

**Comment by AudriusButkevicius** [comment]
My usecase of syncthing is 80mb or so, so I am a light user so it's hard for me to evaluate what's slow and what's fast.

Since you said it was slow, I was intrigued how slow, and if it's really slow, some digging around could be done to figure out why (as it's not doing a lot of magic).
I'd be interested to know what was hitting the cap, CPU, Memory (started swapping), or IO.
And given it's CPU or Memory it would be nice to see heap profiles and cpu profiles (explained in `-help` how to produce them)

**Comment by calmh** [comment]
So... is there a problem here or not? :)

**Comment by AudriusButkevicius** [comment]
I think not, unless uok can reproduce it, as I tried his steps and it didn't work.

**Comment by calmh** [comment]
Closing for the time being, feel free to reopen if reproducible!

**Comment by uok** [comment]
I do not see button to reopen...

I can reproduce it with a folder A (4 files, ~20GB total), and a simple rename to folder B. It seems that Syncthing starts the transfer/copy of existing blocks to folder B, then interrupts action (there are no connection errors, panic logs, network problems, etc. visible - also both computers enough RAM and disk space), then deletes existing files in folder A and continues to transfer complete files to folder B.

**Comment by AudriusButkevicius** [comment]
It seems that you rename the folder mid scan?

**Comment by uok** [comment]
no, everything is fully synced before renaming

**Comment by AudriusButkevicius** [comment]
Can you get a trace by setting env var `STTRACE=model,files`  and paste the log to some pastebin?

I tried with a single 1GB file and it worked fine.

**Comment by AudriusButkevicius** [comment]
This should now be fixed by the more efficient renaming, but the actual cause is still unknown.

**Comment by Deleetdk** [comment]
I'm still getting lots of problems with moving folders. It causes annoying situations where it's difficult to see which folder has the newest files. The dates are not always right!

I'm syncing between Linux and Windows (v0.14.11, Windows (64 bit)).

**Comment by AudriusButkevicius** [comment]
Dates of folders are not synced, as explicitly stated in the documentation.

**Comment by Deleetdk** [comment]
What is the solution to moving folders around without getting duplicated versions of different dates?

**Comment by AudriusButkevicius** [comment]
What do you mean by duplicated versions of different dates? 

We don't preserve folder dates if that is what you are asking, so we don't have a solution for that

**Comment by Deleetdk** [comment]
Typical situation.

1. I have a project, X, in ~/projects/X.
2. I finished this project at some point and move the X folder to ~/projects/finished/2016/X.
3. Some time later, I find that I have two versions of the X folder. One at ~/projects/X and one at ~/projects/finished/X.
4. Usually this means that the one at ~/projects/X is an old copy that got transferred back from the cloud. It fails to understand I moved the folder.

**Comment by AudriusButkevicius** [comment]
No, that usually means you either have conflicts (modifications on the other side by some code indexer for example) or there is something wrong with permissions/modification timestamps on the other side. If you can reliably reproduce it in a vanilla environment, you can open a thread on the forum for a debugging session.

**Comment by Deleetdk** [comment]
The other node is a passive node. There cannot be any conflicts because no changes are made there.

**Comment by AudriusButkevicius** [comment]
I am going to stop replying here, as I've explained above this discussion should happen on the forum.
