### ISSUE TITLE
Better restart message during auto-upgrade

### ISSUE THREAD

**Issue by juh2** [syncthing/syncthing#1248]
Just a small issue. When Syncthing is upgraded we see a message that network or syncthing is unavailable (cannot remember the exact wording). To prevent confusion it would be better, if we see a message which states something like this: Syncthing is restarting and will be available in a few seconds.

**Comment by calmh** [comment]
You mean when it upgrades automatically, as opposed to when you press the button in the GUI?

**Comment by juh2** [comment]
No. When Syncthing upgrades I see AFAICS this message:

    syncthing-master/gui/index.html:
        420    
        421  
        422:   <modal id="networkError" status="danger" icon="exclamation-sign" title="{{'Connection Error' | translate}}">
        423      <p translate>
        424        Syncthing seems to be down, or there is a problem with your Internet connection.   Retrying&hellip;

It's just a small annoyance as Syncthing restarts immediately. But new users might be confused.

**Comment by AudriusButkevicius** [comment]
Basically, we need to need to fire off an event when we realize we've upgraded sucesfully, and handle that in the UI.

**Comment by beta1440** [comment]
Is this still an issue?

**Comment by lfantonioli** [comment]
Wasn't this issue fixed by following the commit? https://github.com/syncthing/syncthing/commit/26d52bedb3d83d7e54f5aa8f4b3f6cc7058ff88a

**Comment by marbens-arch** [comment]
> Wasn't this issue fixed by following the commit? [26d52be](https://github.com/syncthing/syncthing/commit/26d52bedb3d83d7e54f5aa8f4b3f6cc7058ff88a)

Kind of. I did some testing, it does throw a warning message saying that it will restart in 1 minute after it automatically upgrades, but it still shows the old "Syncthing seems to be down" dialog when it actually restarts.

Manual upgrades from the button in the web GUI do use the new "Syncthing is upgrading" dialog.

**Comment by neevets** [comment]
I saw that #10511 addressed part of this, but from testing current versions the UI still shows the generic “Connection Error” dialog during the actual restart phase of auto-upgrade.

The previous PR was closed due to timing concerns, but the underlying UX issue still seems present. I’d like to explore handling the disconnect caused by a known upgrade restart differently from real network errors.
