### ISSUE TITLE
Cannot connect computer with mobile Phone

### ISSUE THREAD

**Issue by SteffenTux** [syncthing/syncthing#1482]
syncthing-APP succsessfull reads the barcode from the desktop of my notebook, but does not connect it.
On the other side laptop adds the mobile phone as equipment but does not connect it. Former versions of syncthing APP workes fine on my mobile phone

**Comment by AudriusButkevicius** [comment]
Wrong repo, and an issue which has been fixed: https://github.com/syncthing/syncthing-android/issues/239

**Comment by SteffenTux** [comment]
I installed the newest version of syncthing app and tried it with a fix IP-adress. Still not works.

**Comment by AudriusButkevicius** [comment]
I am not sure if the fix is released, hence check the web ui on the phone in the meanwhile.

**Comment by SteffenTux** [comment]
Today I installed android version 0.5.21. It's not possible to add equipment to syncthing, because the app crashes, when trying this.

**Comment by AudriusButkevicius** [comment]
It's the wrong repo you are reporting to, as I said.
Check syncthing-android for similar issues.
