### ISSUE TITLE
Folder not reported as invalid if marker missing

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#2654]
See canton7/SyncTrayzor#187

The `invalid` field of the `folders` element in `/rest/system/config` used to contain a value if the folder marker was missing, but apparently no longer does so.

**Comment by calmh** [comment]
Somewhat related (in that it concerns the same attribute, and maybe the overall handling of this): #2471

**Comment by scienmind** [comment]
I just want to emphasize the importance of this issue:

At the current state, un-mounting synced storage cause constant crashes on windows clients (SyncTrayzor). 
It makes synchronization of external storage devices very problematic. And in conjunction with #215 , there is no workaround for it.

**Comment by calmh** [comment]
There's no need to crash because of this issue, we have events that publish the folder status. @canton7 what are you doing, polling the config repeatedly to check ... something, and then ... what?

**Comment by canton7** [comment]
I don't crash. When syncthing starts, I fetch the config. For each folder that's marked as valid, I'll start fetching information about it, including `/rest/db/ignores`. Since folders can take a while to be properly loaded, I allow 10 minutes of 500 responses before going "syncthing could not be started successfully" and bailing. 

This regression means that I no longer have a way of telling whether or not a folder is healthy, before I need to start fetching information about it.

**Comment by calmh** [comment]
Yeah. At the very least we should generate events for these folders, idle->error, much like what happens when this changes after startup. 

But the invalid handling should be fixed.

**Comment by canton7** [comment]
There is an event, idle->error, but that event still shows the folder as valid.

**Comment by calmh** [comment]
I think I'll tag this as v0.13 and redo it slightly. It's currently broken because we have two different concepts of folder errors, "invalid" which is (originally) for errors detected at startup - duplicate folder ID, missing path, missing folder marker. But then we also detect errors suddenly during run time - missing path or marker, out of space, ....

We should consolidate all of them to the latter category, with the StateChanged event carrying updates and /rest/db/status returning the current error, if any. The config shouldn't carry error information at all. 

The only error we *need* to detect and handle at startup is the duplicate folder ID, which I'm thinking we can just warn about and drop one of the folders. There is no way to get into that situation using the GUI (barring horrible bugs), so the user can get themselves out of it in the same way they got into it.

**Comment by canton7** [comment]
I need to know, at a defined point during startup, whether or not there are any problems with the folder. I can't, for example, wait around to see whether or not a StateChanged event pops up telling me the folder's bad (with a lack of event indicating it's good).

Also a level of backwards compatibility with 0.11 would be very much appreciated!

**Comment by calmh** [comment]
> I can't, for example, wait around to see whether or not a StateChanged event pops up telling me the folder's bad (with a lack of event indicating it's good).

Why not? Even if it's good now, it may go bad two milliseconds later. Assume folders mentioned in the config are good until notified otherwise?

**Comment by canton7** [comment]
Because if a folder's good, I need to start fetching info about it (ignores, etc). If it's not actually good (but I just didn't realise yet), that's going to fail horribly.

**Comment by calmh** [comment]
But you'll get either good information or an error back when you do. This is the same a moment later; you may get a working ignore list now, and an error the next time you ask...

**Comment by calmh** [comment]
Even if we say the folder is good, it may be bad by the time you receive that information and ask for the ignores.

**Comment by canton7** [comment]
The thing is, errors on various folder-related resources are perfectly normal during startup - if a folder's large, I'll get 500's back for up to several minutes while I try and fetch data about it, until some internal part of Syncthing has finished loading/initialising it. I can't tell the difference between "this failed because it wasn't loaded yet: keep trying", and "this failed because it's invalid".

**Comment by calmh** [comment]
Ah. But in that case, calling /rest/db/status should answer that. You may possible we get an evil `500 Fuck Off` while we're starting up and don't know yet, then as soon as we're running you should get the defined output either with an error or without. This should be the "starting point" as well when connecting to an already running Syncthing for example, when we can't know about events in the past.

**Comment by calmh** [comment]
What the web GUI does, iirc, is to get /rest/system/config for the list of folders and devices etc, then check /rest/db/status?folder=... for each folder, then keep that live by event updates.

**Comment by calmh** [comment]
So I'm mostly proposing to remove the single, weird class of errors that would have already shown up in the config and put all those in the /rest/db/status response, where we would already be exposing all other errors that occurred after startup. So technically you could even ignore the events and just poll /rest/db/status, except not recommended for performance reasons.

**Comment by canton7** [comment]
Right, if you promise that `/rest/db/status` will only ever 500 on my during startup, I can work with that. I was fetching the ignores before the status.

**Comment by calmh** [comment]
I promise. In fact, I think it doesn't do even that. It even accepts a completely nonexistent folder, which it should instead return 404 or something for.

**Comment by canton7** [comment]
I'm lost - will it return 500 or 404 during startup?

**Comment by calmh** [comment]
I don't see a reason for it ever returning an error during startup. It should return correct data the instant the API is listning on it's socket as far as I can tell.

**Comment by canton7** [comment]
So once I've fetched `/rest/db/status`, how do I know when it's "safe" to start trying to fetch `/rest/db/ignores`?

By "safe" I mean that any 500's I see are due to an error'd folder, not due to it still starting.

**Comment by calmh** [comment]
I don't think you should ever get a 500 from /rest/db/ignores either due to startup being in progress. Are you sure this happens?

**Comment by canton7** [comment]
It certainly used to - let me check again. It definitely did during the 0.11 era, and I still need to support that.

**Comment by calmh** [comment]
Fairly sure it shouldn't. The reasons I see for returning a 500 are

- "folder does not exist" according to our internal state. But we add folders to this state before starting the API so there is no interval of unknown-ness here
- "folder marker missing" this is badness, can happen any time, but you'll see the same error in /rest/db/status
- weird error opening the `.stignore`, other than it not existing which is fine

**Comment by canton7** [comment]
See https://github.com/syncthing/syncthing/issues/1659

**Comment by calmh** [comment]
Indeed. That's no longer the case. At that point in time we started the API first, then started adding folders and stuff. The order is inverted nowadays, for some good reason I've forgotten, but at the very least it means there is no intermediate state where we claim folders don't exist that actually do and so on.  At the moment, starting the API is pretty much the last thing we do just before we start connecting to stuff.

**Comment by canton7** [comment]
When was this changed?

**Comment by calmh** [comment]
But on the other hand if you need to take care of v0.11 clients this may not matter to you. Forget about v0.11 when we hit v0.13 I'd say.

**Comment by calmh** [comment]
Hang on, I'll check.

**Comment by canton7** [comment]
Yeah I plan to - current version, and the one before it.

**Comment by calmh** [comment]
145f8c7

**Comment by canton7** [comment]
So 0.11.9? That's probably old enough in the 0.11 line for me to ignore anything older - let me try changing tactics, see if that works. Thanks!

**Comment by AudriusButkevicius** [comment]
This is fixed/mitigated by 6d357211b2809df2e021364843b36c195799fe41
