### ISSUE TITLE
Discovering new files in a deleted directory does not resurrect the directory

### ISSUE THREAD

**Issue by rkfg** [syncthing/syncthing#4475]
So for some unknown reason the puller gets stuck on some directory being unable to delete it. The directory was deleted on the remote device (don't know when exactly, maybe yesterday) but can't be removed on the local one. Here's the log:

```
[xxxx] 2017/10/31 13:10:51.599131 logfs.go:61: DEBUG: mtimefs.go:55 basic /home/dina/Dropbox/ Lstat . {0xc4203e21a0} <nil>
[xxxx] 2017/10/31 13:10:51.599188 logfs.go:61: DEBUG: mtimefs.go:55 basic /home/dina/Dropbox/ Lstat моё {0xc4203e2270} <nil>
[xxxx] 2017/10/31 13:10:51.599230 rwfolder.go:570: DEBUG: Deleting dir моё/МедСправки орто
[xxxx] 2017/10/31 13:10:51.599326 logfs.go:55: DEBUG: <autogenerated>:1 basic /home/dina/Dropbox/ DirNames моё/МедСправки орто [Справка.bmp Выписка1.bmp Thumbs.db Выписка2.bmp Акт.bmp] <nil>
[xxxx] 2017/10/31 13:10:51.599353 logfs.go:115: DEBUG: <autogenerated>:1 basic /home/dina/Dropbox/ Stat моё {0xc4203e2340} <nil>
[xxxx] 2017/10/31 13:10:51.599385 logfs.go:97: DEBUG: <autogenerated>:1 basic /home/dina/Dropbox/ Remove моё/МедСправки орто remove /home/dina/Dropbox/моё/МедСправки орто: directory not empty
[xxxx] 2017/10/31 13:10:51.599399 logfs.go:61: DEBUG: mtimefs.go:55 basic /home/dina/Dropbox/ Lstat моё/МедСправки орто {0xc4203e2410} <nil>
[xxxx] 2017/10/31 13:10:51.599426 rwfolder.go:1675: INFO: Puller (folder "dina-dropbox", file "моё/МедСправки орто"): delete dir: remove /home/dina/Dropbox/моё/МедСправки орто: directory not empty
[xxxx] 2017/10/31 13:10:51.599454 rwfolder.go:227: DEBUG: sendReceiveFolder/dina-dropbox@0xc420087400 changed 1
[xxxx] 2017/10/31 13:10:51.599466 rwfolder.go:325: DEBUG: sendReceiveFolder/dina-dropbox@0xc420087400 c 1 p 16
[xxxx] 2017/10/31 13:10:51.629165 logfs.go:61: DEBUG: mtimefs.go:55 basic /home/dina/Dropbox/ Lstat . {0xc42148a0d0} <nil>
[xxxx] 2017/10/31 13:10:51.629228 logfs.go:61: DEBUG: mtimefs.go:55 basic /home/dina/Dropbox/ Lstat моё {0xc42148a4e0} <nil>
[xxxx] 2017/10/31 13:10:51.629289 rwfolder.go:570: DEBUG: Deleting dir моё/МедСправки орто
[xxxx] 2017/10/31 13:10:51.629371 logfs.go:55: DEBUG: <autogenerated>:1 basic /home/dina/Dropbox/ DirNames моё/МедСправки орто [Справка.bmp Выписка1.bmp Thumbs.db Выписка2.bmp Акт.bmp] <nil>
[xxxx] 2017/10/31 13:10:51.629406 logfs.go:115: DEBUG: <autogenerated>:1 basic /home/dina/Dropbox/ Stat моё {0xc42148a5b0} <nil>
[xxxx] 2017/10/31 13:10:51.629437 logfs.go:97: DEBUG: <autogenerated>:1 basic /home/dina/Dropbox/ Remove моё/МедСправки орто remove /home/dina/Dropbox/моё/МедСправки орто: directory not empty
[xxxx] 2017/10/31 13:10:51.629458 logfs.go:61: DEBUG: mtimefs.go:55 basic /home/dina/Dropbox/ Lstat моё/МедСправки орто {0xc42148a680} <nil>
[xxxx] 2017/10/31 13:10:51.629503 rwfolder.go:227: DEBUG: sendReceiveFolder/dina-dropbox@0xc420087400 changed 1
[xxxx] 2017/10/31 13:10:51.629518 rwfolder.go:325: DEBUG: sendReceiveFolder/dina-dropbox@0xc420087400 c 1 p 16
[xxxx] 2017/10/31 13:10:51.656975 logfs.go:61: DEBUG: mtimefs.go:55 basic /home/dina/Dropbox/ Lstat . {0xc42148a750} <nil>
[xxxx] 2017/10/31 13:10:51.657036 logfs.go:61: DEBUG: mtimefs.go:55 basic /home/dina/Dropbox/ Lstat моё {0xc42148a820} <nil>
[xxxx] 2017/10/31 13:10:51.657110 rwfolder.go:570: DEBUG: Deleting dir моё/МедСправки орто
[xxxx] 2017/10/31 13:10:51.657216 logfs.go:55: DEBUG: <autogenerated>:1 basic /home/dina/Dropbox/ DirNames моё/МедСправки орто [Справка.bmp Выписка1.bmp Thumbs.db Выписка2.bmp Акт.bmp] <nil>
[xxxx] 2017/10/31 13:10:51.657265 logfs.go:115: DEBUG: <autogenerated>:1 basic /home/dina/Dropbox/ Stat моё {0xc420cbe000} <nil>
[xxxx] 2017/10/31 13:10:51.657314 logfs.go:97: DEBUG: <autogenerated>:1 basic /home/dina/Dropbox/ Remove моё/МедСправки орто remove /home/dina/Dropbox/моё/МедСправки орто: directory not empty
[xxxx] 2017/10/31 13:10:51.657330 logfs.go:61: DEBUG: mtimefs.go:55 basic /home/dina/Dropbox/ Lstat моё/МедСправки орто {0xc420cbe0d0} <nil>
[xxxx] 2017/10/31 13:10:51.657376 rwfolder.go:227: DEBUG: sendReceiveFolder/dina-dropbox@0xc420087400 changed 1
[xxxx] 2017/10/31 13:10:51.657399 rwfolder.go:264: INFO: Folder dina-dropbox isn't making progress. Pausing puller for 1m0s.
[xxxx] 2017/10/31 13:10:51.657412 rwfolder.go:265: DEBUG: sendReceiveFolder/dina-dropbox@0xc420087400 next pull in 1m0s
[xxxx] 2017/10/31 13:10:51.687779 progressemitter.go:240: DEBUG: progress emitter: bytes completed for dina-dropbox: 0
```

The sync progress is stuck seemingly forever. Of course I can remove the directory, rescan and it'll work again for some days or weeks only to get stuck on another directory again. This happens regularly but I see no pattern as that happens to another Syncthing user, I only provide the server. The directories and files are renamed and deleted pretty often, not always there's a connection to the server, sometimes Syncthing disconnects and never reconnects again though Internet is working fine (subject to other issue). It's pretty long-standing now, I remember this happening even a year ago.

### Version Information

Syncthing Version: v0.14.40-rc.4 (server), 0.14.39 (client)
OS Version: Debian Jessie (server), Ubuntu 14.04 (client)
Browser Version: Chrome latest

**Comment by AudriusButkevicius** [comment]
Please read the docs about ignore file and it's effect on ability to remove directories.

**Comment by rkfg** [comment]
The .stignore file isn't used anywhere on the clients. Or am I missing something?

**Comment by AudriusButkevicius** [comment]
```
/home/dina/Dropbox/ DirNames моё/МедСправки орто [Справка.bmp Выписка1.bmp Thumbs.db Выписка2.bmp Акт.bmp]

remove /home/dina/Dropbox/моё/МедСправки орто: directory not empty
```

There is something in the directory we are not aware off, which means it either hasn't been scanned (for whatever reason, if you delayed the scan, use inotify that's broker or whatever) or it's ignored.

**Comment by rkfg** [comment]
It's _not_ ignored, we need to synchronize absolutely everything. We're using Syncthing-GTK on the client with inotify watcher and just plain syncthing binary on the server with default rescan intervals (60 seconds). I restarted Syncthing on the client but it didn't help. The server rescans often enough to be aware of it and that directory in .stversions has last access time of 13 hours ago (probably when it has been deleted). Even if inotify is the case, if it causes some races inside ST this needs to be fixed.

**Comment by AudriusButkevicius** [comment]
.stversions has nothing todo with scanning.

If you rescan manually (given inotify was unreliable), I'd expect it to solve itself, unless things are ignored.

**Comment by rkfg** [comment]
I mentioned .stversions because I had no other way to find when the directory was removed (it could be hours or months, I don't check those logs often). I know what that is.

Also, the directory removal originally happened on the other client device (same setup as the described client), it's been synced to the server. Later the client experiencing the issue has connected to the server and could not synchronize that directory (i.e. remove it). The clients almost never connect to each other (work and home devices), they both connect to the server.

Unfortunately, the issue doesn't solve itself. As in the previous occasions I always have to manually remove the offending directory or it continues to spam the log and pause the puller. Does pausing the puller because of this error affect synchronizing other files?

**Comment by AudriusButkevicius** [comment]
Actually, this got me thinking. @calmh it seems that given we don't track any metadata about directories, this directory is just out of date, and the fact that there is new files in the directory does not bump it's version, so you end up in a dead end. Do we have any ticket for this, or ideas how to solve it? Bump version of every path component along the path we found?

**Comment by AudriusButkevicius** [comment]
Puller tries to process as much as it can, so no, this should not affect other items.

**Comment by AudriusButkevicius** [comment]
@calmh do we have an issue like this open? Even graph puller wouldn't solve this, as we need a graph scanner.

**Comment by rkfg** [comment]
Could you please open this issue until a duplicate is found? It happened to myself recently as well and my connection is much better than that of the other user. Still, this sync lockup happened. The directory has been half-empty, i.e. some of the files were successfully deleted but not all and ST flooded the log with the aforementioned messages about a non-empty directory.

**Comment by AudriusButkevicius** [comment]
I am waiting for @calmh to reply.

**Comment by calmh** [comment]
This is #114 which I seem to have thought was resolved at some point. Might as well make this the new one instead.

As for solving it, I'm not sure. I guess the bug is that we don't see the dependency between the directory and it's contents. Bumping the version (and making sure things like deleted flags are set/cleared correctly) of parents on change sounds reasonable, although expensive.

**Comment by imsodin** [comment]
A cheaper way would be to check for the reason of a folder deletion failure: If it is due to files existing below it in the database, bump the version instead of deleting, if it is due to ignored files, give a more descriptive error message (#4476). Does that sound reasonable?

**Comment by rkfg** [comment]
FYI, this either isn't solved or the issue is somewhere else. I still get these errors and the puller gets paused:
```
Feb 05 12:17:25 leaseweb-new syncthing[520]: [NKCV4] 2018/02/05 12:17:25.447445 rwfolder.go:1796: INFO: Puller (folder dina-dropbox, file "GREAT BRITAIN/Great Britain. Pictures/Great Britain -Scotland"): delete dir: directory is not empty
Feb 05 12:17:25 leaseweb-new syncthing[520]: [NKCV4] 2018/02/05 12:17:25.448730 rwfolder.go:1796: INFO: Puller (folder dina-dropbox, file "GREAT BRITAIN/Great Britain. Pictures/Great Britain - England, Wales"): delete dir: directory is not empty
Feb 05 12:17:25 leaseweb-new syncthing[520]: [NKCV4] 2018/02/05 12:17:25.449056 rwfolder.go:1796: INFO: Puller (folder dina-dropbox, file "GREAT BRITAIN/Great Britain. Pictures"): delete dir: directory is not empty
Feb 05 12:17:25 leaseweb-new syncthing[520]: [NKCV4] 2018/02/05 12:17:25.449965 rwfolder.go:1796: INFO: Puller (folder dina-dropbox, file "GREAT BRITAIN/English Royalty. Monarchs and Family"): delete dir: directory is not empty
Feb 05 12:17:25 leaseweb-new syncthing[520]: [NKCV4] 2018/02/05 12:17:25.507278 rwfolder.go:296: INFO: Folder dina-dropbox isn't making progress. Pausing puller for 8m0s.
Feb 05 12:18:11 leaseweb-new syncthing[520]: [NKCV4] 2018/02/05 12:18:11.419054 rwfolder.go:1796: INFO: Puller (folder dina-dropbox, file "GREAT BRITAIN/Great Britain. Pictures/Great Britain -Scotland"): delete dir: directory is not empty
Feb 05 12:18:11 leaseweb-new syncthing[520]: [NKCV4] 2018/02/05 12:18:11.421073 rwfolder.go:1796: INFO: Puller (folder dina-dropbox, file "GREAT BRITAIN/Great Britain. Pictures/Great Britain - England, Wales"): delete dir: directory is not empty
Feb 05 12:18:11 leaseweb-new syncthing[520]: [NKCV4] 2018/02/05 12:18:11.421581 rwfolder.go:1796: INFO: Puller (folder dina-dropbox, file "GREAT BRITAIN/Great Britain. Pictures"): delete dir: directory is not empty
Feb 05 12:18:11 leaseweb-new syncthing[520]: [NKCV4] 2018/02/05 12:18:11.494843 rwfolder.go:296: INFO: Folder dina-dropbox isn't making progress. Pausing puller for 8m0s.
```
It's still pretty random but when it happens it won't go until I manually delete the directories from the server. How can I get more debug information regarding the issue? It's getting more and more annoying and I don't know how to help. It looks like the user moved and/or renamed the files and directories but for some reason this is not correctly propagated to the server.

**Comment by AudriusButkevicius** [comment]
Well the os states the directory is not empty, so check what is being left behind there.

**Comment by AudriusButkevicius** [comment]
And the files are not ignored on either side?

**Comment by AudriusButkevicius** [comment]
STTRACE=model would be interesting to see.

**Comment by rkfg** [comment]
Like I said in the beginning, we don't use any ignores. If this is such a big issue (as you seem to ask each and every time about ignores), I think it would be nice to make this more obvious to the user. Like, if ST encounters any problem with syncing and the file/directory in question is ignored it must be said so instead of dumping cryptic errors in the log. The way ignores are implemented now is suboptimal if it may result in errors/warnings instead of just skipping the files.

I have removed the directories already so the error is gone for now. But since it happens frequently enough I'm sure I'll encounter it again soon.

**Comment by AudriusButkevicius** [comment]
Well I want to understand how this happens, and the only way I could explain this is ignores. Since a recent version the error messages should be better.

**Comment by rkfg** [comment]
Ok, we've already removed the ignores out of the equation so what's left? I think fuzzy testing could help. Setup 3-4 nodes with a deep enough directory structure (5-6 levels), each of them containing 10-100 files (full unicode range must be used in the file/directory names, not just ASCII), then rename the directories and files randomly, add spaces to the names and so on, kicking rescanning at any time randomly as well. All of this could be done in a fully automatic way. It could help finding race conditions and such. We use inotify watcher via Syncthing-GTK but it absolutely should not be a problem. The watcher just starts the rescan process and it could possibly start at any time if we only used a timer. So basically there's no difference, and if there's a race condition it could be hit with whatever method (I could also press the rescan button in the middle of deleting/renaming a bunch of files and directories and it absolutely must not lead to this stuck behavior).

**Comment by AudriusButkevicius** [comment]
Well, I don't know what we are looking for, so if you see a trend in what seems to cause it and you manage to get on a repro, give us a shout. In the meanwhile debug logs I asked for could help. Perhaps the OS returns some funky order for non-ascii tree walks, etc.
