### ISSUE TITLE
Remote encrypted share isn't synced for the first time

### ISSUE THREAD

**Issue by jvalrog** [syncthing/syncthing#8041]
Syncthing v1.18.4
Ubuntu 20.04

Just shared a folder as encrypted to another remote host and in the remote host GUI it said "Up to date" but the folder was still empty.

Had to restart syncthing on the remote host for the folder to get populated.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by AudriusButkevicius** [comment]
Actually, hastily closed this, but I think this is already fixed.

**Comment by tomasz1986** [comment]
> Actually, hastily closed this, but I think this is already fixed.

Not fixed. I've experienced the same issues in the recent `main`. I haven't had enough time to proceed with proper reproduction and debug logging, so I couldn't report it yet.

**Comment by masksshow** [comment]
I confirm. The error persists.

**Comment by scuba-tech** [comment]
I confirm as well. I have to (predictably/every time) restart the receiving endpoint's Syncthing service, after adding an encrypted folder.

I've confirmed this behavior 6/6 times on two devices (Raspian + KDE).
Hope this confirmation helps.

**Comment by jhertel** [comment]
I have what seems to be the same issue, just with unencrypted files, so the issue might not only be with encrypted files.

v1.19.0, Windows (64-bit Intel/AMD)
Build 2022-01-24

When accepting a new shared folder from another computer, the WebUI on the "receiving" computer immediately says "Up to date" for that folder, even though the receiving computer's folder is in fact still empty and the other computer has files in the corresponding folder. I tried waiting 5-10 minutes after adding the folder, but Syncthing still didn't discover that the folders where out of sync, and still claimed untruthfully that the folder was "Up to date" (it would at least be better if it said "Unknown state" or something until it knows for certain). This continues until I press "Pause All" and then "Resume All" under "Remote Devices" – then it immediately discovers the folder is out of sync and starts updating. All the time Syncthing was happily and correctly syncing another folder between the same two computers, which showed fine on the WebUI, so Syncthing and the connection was in fact active and functioning.
