### ISSUE TITLE
Syncing slow when web gui open

### ISSUE THREAD

**Issue by mmack** [syncthing/syncthing#867]
Hey Guys,
i have syncthing installed on my synology nas. And i have a really strange performance issue.

I can't better describe the issue other than this: If i have the web ui of the nas open in my browser, syncing slows down to a few bytes per second. If i close it it raises immediately to about 50Mbit.

Maybe this helps you guys to improve this great product! :)

Max

**Comment by BlackEdder** [comment]
On the forum this issue comes up quite often (and I experience it myself on the raspberrypi). It seems to occur primarily in cases where people access the webgui remotely.

**Comment by AudriusButkevicius** [comment]
I don't think it matters to be honest.
I guess someone just needs to run profiling to figure out what's causing it.

**Comment by facastagnini** [comment]
I can confirm the same behavior.

Scenario:
version: 0.10.21
iMac [MacOS 10.10.1] <---> MacBook Pro [MacOS 10.10.1]

How can I help?

**Comment by AudriusButkevicius** [comment]
`-help` explains how to run a cpu profile. Make sure its transfering stuff to capture the right stuff in the profile.

**Comment by facastagnini** [comment]
Here we go: http://www.filedropper.com/cpu-1653

Please let me know it if works.
Thanks

**Comment by AudriusButkevicius** [comment]
what version was this produced with (os, bits, syncthing version)?

**Comment by risoul** [comment]
Same issue here, no problem when I do not use web Gui ou GTK Gui. It would be fine to inform users about that, I was near to quit syncthing to btsync because of that.

**Comment by AudriusButkevicius** [comment]
It only happens on some machines.
@facastagnini still hasn't answered my question in order for me to try and work out what's causing it.

**Comment by risoul** [comment]
It happens on mine.
Majaro Linux 64 bits/ Kernel 3.16 / Thinkpad T410 Core i5 / Syncthing v0.10.21 from AUR
Let me know if I can do anything (log...)

**Comment by AudriusButkevicius** [comment]
Well it's the same steps as I've explained above.

**Comment by risoul** [comment]
Ran syncthinf STCPUPROFILE
Unable to find any pprof file

"Make sure its transfering stuff to capture the right stuff in the profile."
Could you explain?

**Comment by facastagnini** [comment]
@risoul I think I execute something like: $ STCPUPROFILE=1 syncthing
That will create a file. Make sure you shutdown syncthing before share it.

@AudriusButkevicius Sorry for the long delay, the NYC weather is giving the time to look at this again :)

I run this between two mac:

Alice
syncthing v0.10.21 (go1.4.1 darwin-amd64 default)
iMac [MacOS 10.10.1 Intel 64bits] 

Bob
syncthing v0.10.21 (go1.4.1 darwin-amd64 default)
MacBook Pro [MacOS 10.10.1 Intel 64bits]

**Comment by AudriusButkevicius** [comment]
"Make sure its transfering stuff to capture the right stuff in the profile." 
This ticket is about slow transfers when the UI is open, make sure that you are running the profile while this bug is being experienced.

**Comment by risoul** [comment]
@facastagnini Thanks
@AudriusButkevicius Sorry, I thought this ticket was about CPU, because I found it searching CPU usage problem.
No transfers problem for me, 2.5 Mio/s on local network, but huge cpu usage when gui is open.
Here is the pprof recorded when problen occur: http://dl.free.fr/fQcdE2IW7

**Comment by AudriusButkevicius** [comment]
@risoul same question: what version was this produced with (os, bits, syncthing version)?
I'll try and look at these later tonight.

**Comment by AudriusButkevicius** [comment]
Also, the link you've given, it's not clear what to click to download.

**Comment by facastagnini** [comment]
hahaha, I couldn't find it neither

**Comment by risoul** [comment]
Produced with Majaro Linux 64 bits/ Kernel 3.16 / Thinkpad T410 Core i5 / Syncthing v0.10.21 from AUR
Sorry for the link, do not remember all that stuff... Here is a better one: http://www.filedropper.com/cpu-17967

**Comment by AudriusButkevicius** [comment]
Both of the profiles don't seem to tell me much. Apart from a crazy amount of requests which could potentially cause lock contention.

Attaching for reference for @calmh to look at.
[Linux](https://cloud.githubusercontent.com/assets/1144861/5926860/33015c4a-a666-11e4-9669-cec30a4b4477.jpg)
[OSX](https://cloud.githubusercontent.com/assets/1144861/5926864/37577efa-a666-11e4-93d4-37acf1af9bea.jpg)

**Comment by AudriusButkevicius** [comment]
Can you guys try this build once it finishes building:
http://build.syncthing.net/job/syncthing-branch/1689/

This time run with `STBLOCKPROFILE=1`

**Comment by canton7** [comment]
Maybe related: if you leave the GUI open, it's not uncommon to see requests start to pile up. That is, the GUI has done a set of polls, but these haven't all been responded to when the next set of polls is sent out. Once this starts to happen, it snowballs: I can end up with hundreds of HTTP requests which are all pending, and yet more are created every couple of seconds.

**Comment by AudriusButkevicius** [comment]
We only perform requests once every 10 seconds, hence if we fail to respond within 10 seconds, that's already an issue.

I am keen to see which requests start snowballing.

**Comment by canton7** [comment]
I'll make a note of it (in a separate issue, and link it in) when I next see it.

**Comment by devurandom** [comment]
Instead of performing HTTP requests every Ns, wouldn't it be better to use BOSH?

**Comment by Zillode** [comment]
@AudriusButkevicius it is related to https://github.com/syncthing/syncthing/pull/734

**Comment by AudriusButkevicius** [comment]
BOSH?

**Comment by devurandom** [comment]
https://en.wikipedia.org/wiki/BOSH

**Comment by AudriusButkevicius** [comment]
We are using long polling for the events interface, but for how much data I have transferred long polling does not make sense, as the number is constantly changing. This makes the problem worse, not better.

Bosh seems to be slightly different to long polling, but I am not sure I understand the benefits.

**Comment by risoul** [comment]
No more issue for me (high cpu usage when gui open), I use 0.10.25 now and I can keep gui open.

**Comment by AudriusButkevicius** [comment]
Should be fixed in 0.11.

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/commit/454e688c3d626f8e2413d8c0d8acc65c204d8981 Ref commit.
Needs to be adapted by all downstream people for this to work too.

**Comment by EmilioMoreno** [comment]
Hi,
I can confirm this is still happening with v0.11.26. When I open WebUI, bandwidth transfer slows to very low values after all the information is loaded in the WebUI (about 1 min or so). Then, if you have the WebUI open, speed is higher but it does not increases to where it should be, and once you close the webUI and after a while (about 2 min or so), it goes back to the original speed.

In my case, running without webUI open shows 1.5Mbps. When I open WebUI and while it is loading WebUI data it slows down to 100Kbps. Once the data is loaded and while the WebUI is active, speed is about 400Kbps. Closing the WebUI tab gets speed back to 1.5Mbps.

**Comment by AudriusButkevicius** [comment]
What sort of device are you running on?

**Comment by EmilioMoreno** [comment]
on one side i have a synology NAS1813+, (intelAtomD2700, 2 cores with HT, 4GB Ram). 
on the other side, a MacbookPro (intel core 2 Duo, 2.8Ghz, 4 GB Ram).
When i open WebUI on the Synology, everything is slowing down as described.

Cpu is never at 100% and the NAS is responding perfectly.

I have tried renicing all the synching process to -10 in the nas side and it seems that the behaviour is more stable, but if i keep nice to 0, it happens again.

**Comment by AudriusButkevicius** [comment]
I guess its just not getting enough CPU time when doing more then one thing. Also, I'd check how many threads syncthing spawns, as it should be number of cores usually.

**Comment by EmilioMoreno** [comment]
The number of main processes is 2, which matches the number of cores in NAS side. However, taking a look at htop i can see the number of threads is higher, about 31.

In the MAcbookpro side, 1 process, which matches the number of cores too.

If i do the same test in the MacBook Pro side (open the WebUI), even if i have the process with nice -15, the network transfer slows heavily.

**Comment by AudriusButkevicius** [comment]
We always have 2 processes when not launched via service manager. I guess you could provide a block profile and a cpu profile, but it's not obvious to me how to debug this. @calmh ideas?

Should we make the summarySvc pause configurable?

**Comment by calmh** [comment]
Whichever way we twist and turn, providing info for the GUI is a lot of extra work, that is avoided by not having the GUI up. The CPU isn't the only thing here, there's also lots of database reads added by the summary service, which can be expensive if the db is a slow NAS disk.

I wouldn't worry about the number of threads and processes and the niceness, and just accept the fact that not having the GUI open is a performance win.

In the long run, not having to do database scans to get at the information we need would be an ever larger win...

**Comment by EmilioMoreno** [comment]
I agree that non-having the WebUI will provide the best performance increase :-), but at least people (at least myself) would need a way to see what is happening. I only need to see what is current status of each end, what file is being transferred and the speed, but having to enable the debug in different modules to see how it goes is not practical.

Anyway, decreasing the niceness of the process to -15 has decreased the impact to open WebUI on the NAS side, so at least i can make myself an idea.

**Comment by Nattuma** [comment]
Okay I have the same problem... I am however wondering what a web Gui is in the first place. Does it simply relate to opening sync thing in a webbrowser? Or is there some function I need to manually shut off to make sure webgui is not running?

**Comment by AudriusButkevicius** [comment]
No, just close the browser tab.

**Comment by chrisf4lc0n** [comment]
It seems to significantly raise the CPU usage, but still staying low at around 7% with E3-1230 and just around 2% with the E5-2697v2 which it still not enough to slow the transfers down on the 6 ZFS RAIDZ 10 config... Once the WebUI is shut transfer tripples to what it should be for 70 mbps connection...

**Comment by AudriusButkevicius** [comment]
I think its potentially lock contention related to calculating the UI info.
