### ISSUE TITLE
Display error in 1.26 with login screen

### ISSUE THREAD

**Issue by canis54** [syncthing/syncthing#9208]
I reverted back to http-basic-auth in 1.26. Essential information about the authentication with the new login screen is not displayed to me. There is full access after authorization because I can, for example, reactivate Basic Auth via the GUI. Browser: Chrome 118. In Firefox the GUI doesn't even build completely, some JS restarts the build every few seconds. After activating http-basic-auth, the GUI works again as usual in Firefox.
![2023-11-09_09-17](https://github.com/syncthing/syncthing/assets/33317545/eef74df0-6edc-4c59-b4ee-0f8b631142c7)
![2023-11-09_09-18](https://github.com/syncthing/syncthing/assets/33317545/43729a65-9367-4b0b-82b1-14dd7a4a7037)

**Comment by bt90** [comment]
We're aware of the issue but weren't able reproduce it yet. Your screenshot is pretty interesting though, as half of the UI appears to work. This almost looks like some kind of race condition.

**Comment by canis54** [comment]
I can now add the following observation. After I was able to observe the error pattern on two hosts with syncthing increased from 1.25 to 1.26, I switched back to basic-auth as written and the error disappeared. Now I have switched two more hosts and the error didn't even occur on them in the same browser session with the new login mask, which surprised me. Then I switched the two first migrated hosts back to the new login mask as a cross-check, and lo and behold, the error disappeared, as if Chrome had to get used to it... If I can do anything to help find the cause, let me do so let me know.

**Comment by yuri-273** [comment]
Doesn't work for me in Chrome Version 119.0.6045.124 (Official Build) (64-bit).
But it works in Firefox and Edge.
![Screenshot 2023-11-10 003926](https://github.com/syncthing/syncthing/assets/150396699/5f7087fa-b086-45be-bc5a-966342c7f6ef)

**Comment by yuri-273** [comment]
![image](https://github.com/syncthing/syncthing/assets/150396699/e6254f24-a62f-4d1e-ae4a-7040365edf14)
Firefox 119.0.1 (64-bit)

**Comment by bt90** [comment]
@yuri-273 can you open the developer console in Chrome by pressing the F12 key? I'd be interested to see which cookies are present. Redacting the value column is enough.

https://developer.chrome.com/docs/devtools/application/cookies/

**Comment by keenwon** [comment]
I just experienced the same issue, and I fixed it by clearing cookies. It seems there were 2 cookies named `sessionid-xxxx`

**Comment by yuri-273** [comment]
Deleted cookies. The problem is not solved.
![image](https://github.com/syncthing/syncthing/assets/150396699/715aa9e2-ec72-41e9-913d-5360705b8582)

**Comment by nickalcock** [comment]
I see this too (Chrome 119.0.6045.105). Not tried clearing cookies yet, will do so. Backed down to 1.24, which fortunately worked fine. The only extension I'm using is uBlock Origin, which is not blocking anything on this page.

**Comment by winsphinx** [comment]
I use MS Edge, met this issue also.

**Comment by dapete42** [comment]
I had the "endless reload loop" here (Firefox 118.0.2) on multiple installations of 1.26. Clearing cookies has solved the problem.

These were the cookies before I did that:

| Name             | Path         | Expires | HttpOnly | Secure |
| ---------------- | ------------ | ------- | -------- | ------ |
| CSRF-Token-XXXXX | /            | Session | false    | false  |
| sessionid-XXXXX  | /            | Session | false    | true   |
| sessionid-XXXXX  | /rest        | Session | false    | true   |
| sessionid-XXXXX  | /rest/svc    | Session | false    | true   |
| sessionid-XXXXX  | /rest/system | Session | false    | true   |

After deleting the cookies and logging in again, only CSRF-Token-XXXXX and the sessionid-XXXXX for path "/" were recreated.

**Comment by keitarobr** [comment]
Had to revert to Basic Auth as well (Chrome here). Clearing cache and cookies did not help. It logged but the interface was broken. Could only login through an anonymous tab.

**Comment by calmh** [comment]
So, my interpretation of all this:

- Previously, we did not set `Path: /` on the cookie. Sometimes it ended up on that path, but we also sometimes polluted the cookie space with `/rest` etc cookies as seen above.
- Currently, we set the cookie on `/` but when *getting* the cookie we sometimes get a random cookie for another path that we didn't set. This is an auth failure so we loop.

We can solve this now by either looking at *all* cookies and verifying that we check the one for `/`, or we can use a new cookie name and the old ones should be irrelevant.

**Comment by calmh** [comment]
If this is urgent for Android I expect the Android people to release an appropr

**Comment by calmh** [comment]
(misclick)

**Comment by davidvedvick** [comment]
> I just experienced the same issue, and I fixed it by clearing cookies. It seems there were 2 cookies named `sessionid-xxxx`

This worked for me as well, thanks!

**Comment by acolomb** [comment]
FWIW, I am hit by this bug as well, especially on Android. Not being able to access the Web GUI there is quite a limitation, so I'd welcome getting out a hotfix release.  Clearing the app's cache, plus the WebView's data and cache didn't help for me.  The fix would need to be released in the backend first though.

**Comment by calmh** [comment]
Yes/no, someone could at least make an Android build with 1.27.0-rc.1 in it to see if it fixes the issue... It's not obvious to me that the login window being presented on Android is caused by this, since it's supposed to add basic-auth headers?

**Comment by imsodin** [comment]
RC release is about to happen.

**Comment by EuPhobos** [comment]
> I just experienced the same issue, and I fixed it by clearing cookies. It seems there were 2 cookies named `sessionid-xxxx`

thank, it work for me too

**Comment by imsodin** [comment]
@everyone No need to report anymore that clearing cookies helps, that's well established.

@opusforlife2 @acolomb and other android users: Please use the android ticket for android stuff.

**Comment by tomasz1986** [comment]
Isn't this expected? You need to log in first in order to see the device name.

**Comment by Matthaiks** [comment]
It's hard-coded in English, though.

**Comment by tomasz1986** [comment]
> It's hard-coded in English, though.

A very good point, but it's a material for a different issue 😉.

**Comment by rmeaux** [comment]
> I use MS Edge, met this issue also. And I found why: I use Nginx proxy manager, and enabled `cache asset`. After disable it, syncthing works well.

I was getting the constant page refresh issue after adding a GUI user and pass. This was the resolution. Thanks!
